services:
  selenium-chrome:
    image: selenium/standalone-chrome:4.24.0
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  selenium-firefox:
    image: selenium/standalone-firefox:4.24.0
    container_name: selenium-firefox
    shm_size: 2gb
    ports:
      - "4445:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
