url=https://www.policybazaar.com/
url2=https://practice.expandtesting.com/
browser=chrome
headless=false
implicit.wait=10
pageload.timeout=30
broken.link.connect.timeout.millis=3000
broken.link.read.timeout.millis=3000
