url=https://www.policybazaar.com/
url2=https://practice.expandtesting.com/
browser=chrome
# Supported browsers: chrome, edge, firefox
headless=false
remote=false
remote.url=http://localhost:4444
remote.chrome.url=http://localhost:4444
remote.firefox.url=http://localhost:4445
implicit.wait=10
pageload.timeout=30
broken.link.connect.timeout.millis=3000
broken.link.read.timeout.millis=3000
